### ISSUE TITLE
is this BEM?

### ISSUE THREAD

**Issue by jsms90** [Akin909/morning-challenge-animated-app-drawer#2]
@Akin909 [This](https://github.com/Akin909/morning-challenge-animated-app-drawer/blob/master/style.css#L62-L74) looks a bit like BEM. Is it supposed to be?

If so, this is a nice way of showing students a convention in action. But then (I think) it should be:
> app-drawer__visible

?

**Comment by mattlub** [comment]
if it's BEM (which it probably should be)
`.app_drawer__button__visible` should be
`.app_drawer__button--visible`

http://getbem.com/naming/
